# Change these first
owner: powerfullz # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Blog
    url: https://blog.l3zc.com
  - name: Raspberry Pi Tunnel
    url: https://rpiblog.l3zc.com
  - name: RSSHub
    url: https://rsshub.l3zc.com
  - name: Iceshrimp
    url: https://social.l3zc.com
  - name: Umami
    url: https://analytics.l3zc.com
  - name: Plausible
    url: https://analytics.nightcity.pub
  - name: Comment API
    url: https://commentapi.nightcity.pub
    expectedStatusCodes:
      - 100
      - 200

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.l3zc.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status
  introTitle: "powerfullz's status page."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
